# I will take the base image only for the required task (119mb)
# Stage 1 (builder) 

FROM python:3.14-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt --target /app/libraries

# Python 3.14 ka kaam idhar tak khatam ho chuka hai kyunki mujhe python se jo bhi chahiye vo /app/libraries me##rakha hua hai

COPY . .

# I will take another base image with even lesser size (minimal)
# Stage 2 (deployer)

FROM gcr.io/distroless/python3-debian12 AS deployer

WORKDIR /app

COPY --from=builder /app/libraries /app/libraries

COPY --from=builder /app .

ENV PYTHONPATH="/app/libraries"

EXPOSE 80

CMD ["run.py"]
